################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../micropython/py/argcheck.c \
../micropython/py/asmbase.c \
../micropython/py/asmthumb.c \
../micropython/py/bc.c \
../micropython/py/binary.c \
../micropython/py/builtinevex.c \
../micropython/py/builtinhelp.c \
../micropython/py/builtinimport.c \
../micropython/py/compile.c \
../micropython/py/cstack.c \
../micropython/py/emitbc.c \
../micropython/py/emitcommon.c \
../micropython/py/emitglue.c \
../micropython/py/emitinlinethumb.c \
../micropython/py/emitnarm.c \
../micropython/py/emitnative.c \
../micropython/py/emitndebug.c \
../micropython/py/emitnrv32.c \
../micropython/py/emitnthumb.c \
../micropython/py/emitnxtensa.c \
../micropython/py/emitnxtensawin.c \
../micropython/py/formatfloat.c \
../micropython/py/frozenmod.c \
../micropython/py/gc.c \
../micropython/py/lexer.c \
../micropython/py/malloc.c \
../micropython/py/map.c \
../micropython/py/modarray.c \
../micropython/py/modbuiltins.c \
../micropython/py/modcmath.c \
../micropython/py/modcollections.c \
../micropython/py/moderrno.c \
../micropython/py/modgc.c \
../micropython/py/modio.c \
../micropython/py/modmath.c \
../micropython/py/modmicropython.c \
../micropython/py/modstruct.c \
../micropython/py/modsys.c \
../micropython/py/modthread.c \
../micropython/py/mpprint.c \
../micropython/py/mpstate.c \
../micropython/py/mpz.c \
../micropython/py/nativeglue.c \
../micropython/py/nlr.c \
../micropython/py/nlraarch64.c \
../micropython/py/nlrmips.c \
../micropython/py/nlrpowerpc.c \
../micropython/py/nlrrv32.c \
../micropython/py/nlrrv64.c \
../micropython/py/nlrsetjmp.c \
../micropython/py/nlrthumb.c \
../micropython/py/nlrx64.c \
../micropython/py/nlrx86.c \
../micropython/py/nlrxtensa.c \
../micropython/py/obj.c \
../micropython/py/objarray.c \
../micropython/py/objattrtuple.c \
../micropython/py/objbool.c \
../micropython/py/objboundmeth.c \
../micropython/py/objcell.c \
../micropython/py/objclosure.c \
../micropython/py/objcode.c \
../micropython/py/objcomplex.c \
../micropython/py/objdeque.c \
../micropython/py/objdict.c \
../micropython/py/objenumerate.c \
../micropython/py/objexcept.c \
../micropython/py/objfilter.c \
../micropython/py/objfloat.c \
../micropython/py/objfun.c \
../micropython/py/objgenerator.c \
../micropython/py/objgetitemiter.c \
../micropython/py/objint.c \
../micropython/py/objint_longlong.c \
../micropython/py/objint_mpz.c \
../micropython/py/objlist.c \
../micropython/py/objmap.c \
../micropython/py/objmodule.c \
../micropython/py/objnamedtuple.c \
../micropython/py/objnone.c \
../micropython/py/objobject.c \
../micropython/py/objpolyiter.c \
../micropython/py/objproperty.c \
../micropython/py/objrange.c \
../micropython/py/objreversed.c \
../micropython/py/objringio.c \
../micropython/py/objset.c \
../micropython/py/objsingleton.c \
../micropython/py/objslice.c \
../micropython/py/objstr.c \
../micropython/py/objstringio.c \
../micropython/py/objstrunicode.c \
../micropython/py/objtuple.c \
../micropython/py/objtype.c \
../micropython/py/objzip.c \
../micropython/py/opmethods.c \
../micropython/py/pairheap.c \
../micropython/py/parse.c \
../micropython/py/parsenum.c \
../micropython/py/parsenumbase.c \
../micropython/py/persistentcode.c \
../micropython/py/profile.c \
../micropython/py/pystack.c \
../micropython/py/qstr.c \
../micropython/py/reader.c \
../micropython/py/repl.c \
../micropython/py/ringbuf.c \
../micropython/py/runtime.c \
../micropython/py/runtime_utils.c \
../micropython/py/scheduler.c \
../micropython/py/scope.c \
../micropython/py/sequence.c \
../micropython/py/showbc.c \
../micropython/py/smallint.c \
../micropython/py/stackctrl.c \
../micropython/py/stream.c \
../micropython/py/unicode.c \
../micropython/py/vm.c \
../micropython/py/vstr.c \
../micropython/py/warning.c 

C_DEPS += \
./micropython/py/argcheck.d \
./micropython/py/asmbase.d \
./micropython/py/asmthumb.d \
./micropython/py/bc.d \
./micropython/py/binary.d \
./micropython/py/builtinevex.d \
./micropython/py/builtinhelp.d \
./micropython/py/builtinimport.d \
./micropython/py/compile.d \
./micropython/py/cstack.d \
./micropython/py/emitbc.d \
./micropython/py/emitcommon.d \
./micropython/py/emitglue.d \
./micropython/py/emitinlinethumb.d \
./micropython/py/emitnarm.d \
./micropython/py/emitnative.d \
./micropython/py/emitndebug.d \
./micropython/py/emitnrv32.d \
./micropython/py/emitnthumb.d \
./micropython/py/emitnxtensa.d \
./micropython/py/emitnxtensawin.d \
./micropython/py/formatfloat.d \
./micropython/py/frozenmod.d \
./micropython/py/gc.d \
./micropython/py/lexer.d \
./micropython/py/malloc.d \
./micropython/py/map.d \
./micropython/py/modarray.d \
./micropython/py/modbuiltins.d \
./micropython/py/modcmath.d \
./micropython/py/modcollections.d \
./micropython/py/moderrno.d \
./micropython/py/modgc.d \
./micropython/py/modio.d \
./micropython/py/modmath.d \
./micropython/py/modmicropython.d \
./micropython/py/modstruct.d \
./micropython/py/modsys.d \
./micropython/py/modthread.d \
./micropython/py/mpprint.d \
./micropython/py/mpstate.d \
./micropython/py/mpz.d \
./micropython/py/nativeglue.d \
./micropython/py/nlr.d \
./micropython/py/nlraarch64.d \
./micropython/py/nlrmips.d \
./micropython/py/nlrpowerpc.d \
./micropython/py/nlrrv32.d \
./micropython/py/nlrrv64.d \
./micropython/py/nlrsetjmp.d \
./micropython/py/nlrthumb.d \
./micropython/py/nlrx64.d \
./micropython/py/nlrx86.d \
./micropython/py/nlrxtensa.d \
./micropython/py/obj.d \
./micropython/py/objarray.d \
./micropython/py/objattrtuple.d \
./micropython/py/objbool.d \
./micropython/py/objboundmeth.d \
./micropython/py/objcell.d \
./micropython/py/objclosure.d \
./micropython/py/objcode.d \
./micropython/py/objcomplex.d \
./micropython/py/objdeque.d \
./micropython/py/objdict.d \
./micropython/py/objenumerate.d \
./micropython/py/objexcept.d \
./micropython/py/objfilter.d \
./micropython/py/objfloat.d \
./micropython/py/objfun.d \
./micropython/py/objgenerator.d \
./micropython/py/objgetitemiter.d \
./micropython/py/objint.d \
./micropython/py/objint_longlong.d \
./micropython/py/objint_mpz.d \
./micropython/py/objlist.d \
./micropython/py/objmap.d \
./micropython/py/objmodule.d \
./micropython/py/objnamedtuple.d \
./micropython/py/objnone.d \
./micropython/py/objobject.d \
./micropython/py/objpolyiter.d \
./micropython/py/objproperty.d \
./micropython/py/objrange.d \
./micropython/py/objreversed.d \
./micropython/py/objringio.d \
./micropython/py/objset.d \
./micropython/py/objsingleton.d \
./micropython/py/objslice.d \
./micropython/py/objstr.d \
./micropython/py/objstringio.d \
./micropython/py/objstrunicode.d \
./micropython/py/objtuple.d \
./micropython/py/objtype.d \
./micropython/py/objzip.d \
./micropython/py/opmethods.d \
./micropython/py/pairheap.d \
./micropython/py/parse.d \
./micropython/py/parsenum.d \
./micropython/py/parsenumbase.d \
./micropython/py/persistentcode.d \
./micropython/py/profile.d \
./micropython/py/pystack.d \
./micropython/py/qstr.d \
./micropython/py/reader.d \
./micropython/py/repl.d \
./micropython/py/ringbuf.d \
./micropython/py/runtime.d \
./micropython/py/runtime_utils.d \
./micropython/py/scheduler.d \
./micropython/py/scope.d \
./micropython/py/sequence.d \
./micropython/py/showbc.d \
./micropython/py/smallint.d \
./micropython/py/stackctrl.d \
./micropython/py/stream.d \
./micropython/py/unicode.d \
./micropython/py/vm.d \
./micropython/py/vstr.d \
./micropython/py/warning.d 

OBJS += \
./micropython/py/argcheck.o \
./micropython/py/asmbase.o \
./micropython/py/asmthumb.o \
./micropython/py/bc.o \
./micropython/py/binary.o \
./micropython/py/builtinevex.o \
./micropython/py/builtinhelp.o \
./micropython/py/builtinimport.o \
./micropython/py/compile.o \
./micropython/py/cstack.o \
./micropython/py/emitbc.o \
./micropython/py/emitcommon.o \
./micropython/py/emitglue.o \
./micropython/py/emitinlinethumb.o \
./micropython/py/emitnarm.o \
./micropython/py/emitnative.o \
./micropython/py/emitndebug.o \
./micropython/py/emitnrv32.o \
./micropython/py/emitnthumb.o \
./micropython/py/emitnxtensa.o \
./micropython/py/emitnxtensawin.o \
./micropython/py/formatfloat.o \
./micropython/py/frozenmod.o \
./micropython/py/gc.o \
./micropython/py/lexer.o \
./micropython/py/malloc.o \
./micropython/py/map.o \
./micropython/py/modarray.o \
./micropython/py/modbuiltins.o \
./micropython/py/modcmath.o \
./micropython/py/modcollections.o \
./micropython/py/moderrno.o \
./micropython/py/modgc.o \
./micropython/py/modio.o \
./micropython/py/modmath.o \
./micropython/py/modmicropython.o \
./micropython/py/modstruct.o \
./micropython/py/modsys.o \
./micropython/py/modthread.o \
./micropython/py/mpprint.o \
./micropython/py/mpstate.o \
./micropython/py/mpz.o \
./micropython/py/nativeglue.o \
./micropython/py/nlr.o \
./micropython/py/nlraarch64.o \
./micropython/py/nlrmips.o \
./micropython/py/nlrpowerpc.o \
./micropython/py/nlrrv32.o \
./micropython/py/nlrrv64.o \
./micropython/py/nlrsetjmp.o \
./micropython/py/nlrthumb.o \
./micropython/py/nlrx64.o \
./micropython/py/nlrx86.o \
./micropython/py/nlrxtensa.o \
./micropython/py/obj.o \
./micropython/py/objarray.o \
./micropython/py/objattrtuple.o \
./micropython/py/objbool.o \
./micropython/py/objboundmeth.o \
./micropython/py/objcell.o \
./micropython/py/objclosure.o \
./micropython/py/objcode.o \
./micropython/py/objcomplex.o \
./micropython/py/objdeque.o \
./micropython/py/objdict.o \
./micropython/py/objenumerate.o \
./micropython/py/objexcept.o \
./micropython/py/objfilter.o \
./micropython/py/objfloat.o \
./micropython/py/objfun.o \
./micropython/py/objgenerator.o \
./micropython/py/objgetitemiter.o \
./micropython/py/objint.o \
./micropython/py/objint_longlong.o \
./micropython/py/objint_mpz.o \
./micropython/py/objlist.o \
./micropython/py/objmap.o \
./micropython/py/objmodule.o \
./micropython/py/objnamedtuple.o \
./micropython/py/objnone.o \
./micropython/py/objobject.o \
./micropython/py/objpolyiter.o \
./micropython/py/objproperty.o \
./micropython/py/objrange.o \
./micropython/py/objreversed.o \
./micropython/py/objringio.o \
./micropython/py/objset.o \
./micropython/py/objsingleton.o \
./micropython/py/objslice.o \
./micropython/py/objstr.o \
./micropython/py/objstringio.o \
./micropython/py/objstrunicode.o \
./micropython/py/objtuple.o \
./micropython/py/objtype.o \
./micropython/py/objzip.o \
./micropython/py/opmethods.o \
./micropython/py/pairheap.o \
./micropython/py/parse.o \
./micropython/py/parsenum.o \
./micropython/py/parsenumbase.o \
./micropython/py/persistentcode.o \
./micropython/py/profile.o \
./micropython/py/pystack.o \
./micropython/py/qstr.o \
./micropython/py/reader.o \
./micropython/py/repl.o \
./micropython/py/ringbuf.o \
./micropython/py/runtime.o \
./micropython/py/runtime_utils.o \
./micropython/py/scheduler.o \
./micropython/py/scope.o \
./micropython/py/sequence.o \
./micropython/py/showbc.o \
./micropython/py/smallint.o \
./micropython/py/stackctrl.o \
./micropython/py/stream.o \
./micropython/py/unicode.o \
./micropython/py/vm.o \
./micropython/py/vstr.o \
./micropython/py/warning.o 

SREC += \
newplan_flat.srec 

MAP += \
newplan_flat.map 


# Each subdirectory must supply rules for building sources it contributes
micropython/py/%.o: ../micropython/py/%.c
	$(file > $@.in,-mthumb -mfloat-abi=hard -mcpu=cortex-m85+nopacbti -O2 -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -fno-strict-aliasing -Wunused -Wuninitialized -Wall -Wextra -Wmissing-declarations -Wconversion -Wpointer-arith -Wshadow -Wlogical-op -Waggregate-return -Wfloat-equal -g -D_RENESAS_RA_ -D_RA_CORE=CM85 -D_RA_ORDINAL=1 -I"C:/Users/demon/Desktop/newplan/workspace/newplan_flat/micropython/py" -I"C:/Users/demon/Desktop/newplan/workspace/newplan_flat/micropython/extmod" -I"C:/Users/demon/Desktop/newplan/workspace/newplan_flat/micropython/shared" -I"C:/Users/demon/Desktop/newplan/workspace/newplan_flat/micropython/genhdr" -I"C:/Users/demon/Desktop/newplan/workspace/newplan_flat/ra_gen" -I"C:/Users/demon/Desktop/newplan/workspace/newplan_flat/micropython" -I"." -I"C:/Users/demon/Desktop/newplan/workspace/newplan_flat/ra_cfg/fsp_cfg/bsp" -I"C:/Users/demon/Desktop/newplan/workspace/newplan_flat/ra_cfg/fsp_cfg" -I"C:/Users/demon/Desktop/newplan/workspace/newplan_flat/src" -I"C:/Users/demon/Desktop/newplan/workspace/newplan_flat/ra/fsp/inc" -I"C:/Users/demon/Desktop/newplan/workspace/newplan_flat/ra/fsp/inc/api" -I"C:/Users/demon/Desktop/newplan/workspace/newplan_flat/ra/fsp/inc/instances" -I"C:/Users/demon/Desktop/newplan/workspace/newplan_flat/ra/arm/CMSIS_6/CMSIS/Core/Include" -std=c99 -Wno-sign-conversion -Wno-conversion -Wno-unused-parameter -Wno-float-equal -flax-vector-conversions --param=min-pagesize=0 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" -c -o "$@" -x c "$<")
	@echo Building file: $< && arm-none-eabi-gcc @"$@.in"

